import axios from 'axios';

const pythonService = 'http://127.0.0.1:5001/execute-code';

async function test() {
    const code = `
def reverseString(s):
    left, right = 0, len(s) - 1
    while left < right:
        s[left], s[right] = s[right], s[left]        
        left += 1
        right -= 1

import sys
import ast

line = sys.stdin.read().strip()
if line:
    try:
        # Evaluate to list
        s = ast.literal_eval(line)
        reverseString(s)
        # Format as list of chars
        print(str(s).replace(" ", ""))
    except:
        print("Invalid input format")
`;

    try {
        const res = await axios.post(pythonService, {
            code,
            language: 'python',
            testCases: [{ input: '"hello"', expectedOutput: '' }]
        });
        console.log("ACTUAL OUTPUT GENERATED BY PYTHON:", res.data.actualOutput);
    } catch (e) {
        console.error(e.message);
    }
}
test();
